"$schema" = 'https://starship.rs/config-schema.json'

# Color palette #
# deep indigo -> #1e1e42
# dark blue   -> #1a3a5a
# steel blue  -> #2d4556
# dark slate  -> #3a3a4a
# chrkl mgnta -> #3d2a3d
# deep plum   -> #4a2a3a
# dark red    -> #4a1a2c


format = """
[](#1e1e42)\
$os\
$username\
[](fg:#1e1e42 bg:#1a3a5a)\
$directory\
[](fg:#1a3a5a bg:#2d4556)\
$git_branch\
$git_status\
[](fg:#2d4556 bg:#3a3a4a)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:#3a3a4a bg:#3d2a3d)\
$docker_context\
[](fg:#3d2a3d bg:#4a2a3a)\
$time\
[ ](fg:#4a2a3a bg:#4a1a2c)\
$cmd_duration\
[ ](fg:#4a1a2c)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#1e1e42"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#1a3a5a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#2d4556"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#2d4556"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#3a3a4a"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#4a2a3a"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 2000
format = "[$duration]($style)"
style = "bg:#4a1a2c"
